# Generated by Django 5.2.7 on 2025-10-01 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('clase_licencia', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('monitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=15)),
                ('tipo_monitor', models.CharField(blank=True, choices=[('institucion', 'Institución'), ('tercero', 'Tercero')], default=None, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id_propietario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=10)),
                ('correo_electronico', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=6, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=15, unique=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.conductor')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('punto', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.jornada')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placas.monitor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id_Estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=15)),
                ('grado', models.CharField(choices=[('preescolar', 'Preescolar'), ('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('septimo', 'Septimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Decimo'), ('once', 'Once')], max_length=10)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.jornada')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placas.vehiculo')),
            ],
        ),
    ]
