# Generated by Django 5.2.7 on 2025-10-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0002_alter_vehiculo_options_vehiculo_cupos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterField(
            model_name='conductor',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='clase_licencia',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='Licencia'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='identificacion',
            field=models.CharField(max_length=15, verbose_name='identificación'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nombres',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='conductor',
            table='conductor',
        ),
    ]
