# Generated by Django 5.2.7 on 2025-10-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0003_alter_conductor_options_alter_conductor_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='identificacion',
            field=models.CharField(max_length=15, verbose_name='Identificación'),
        ),
    ]
