# Generated by Django 5.2.7 on 2025-10-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0004_alter_conductor_identificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propietario',
            options={'verbose_name': 'Propietario', 'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='correo_electronico',
            field=models.CharField(max_length=240, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='identificacion',
            field=models.CharField(max_length=15, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='propietario',
            table='propietario',
        ),
    ]
