# Generated by Django 5.2.7 on 2025-10-02 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0005_alter_propietario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': 'monitor', 'verbose_name_plural': 'monitores'},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(choices=[('preescolar', 'Preescolar'), ('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto'), ('quinto', 'Quinto'), ('sexto', 'Sexto'), ('septimo', 'Septimo'), ('octavo', 'Octavo'), ('noveno', 'Noveno'), ('decimo', 'Decimo'), ('once', 'Once')], max_length=10, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(max_length=15, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='placas.jornada'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='placas.vehiculo'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fin',
            field=models.TimeField(verbose_name='Final'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='inicio',
            field=models.TimeField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='apellidos',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='identificacion',
            field=models.CharField(max_length=15, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='tipo_monitor',
            field=models.CharField(blank=True, choices=[('institucion', 'Institución'), ('tercero', 'Tercero')], default=None, max_length=12, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='hora_llegada',
            field=models.TimeField(verbose_name='Hora llegada'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='hora_salida',
            field=models.TimeField(verbose_name='Hora salida'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='placas.jornada'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento', to='placas.monitor'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='placas.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='placas.conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='placas.propietario'),
        ),
        migrations.AlterModelTable(
            name='jornada',
            table='jornada',
        ),
        migrations.AlterModelTable(
            name='monitor',
            table='monitor',
        ),
        migrations.AlterModelTable(
            name='movimientos',
            table='movimientos',
        ),
    ]
