# Generated by Django 5.2.7 on 2025-10-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0006_alter_jornada_options_alter_monitor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='hora_llegada',
            field=models.DateTimeField(verbose_name='Llegada'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='hora_salida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Salida'),
        ),
    ]
