# Generated by Django 5.2.6 on 2025-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='identificacion',
            field=models.CharField(max_length=15),
        ),
    ]
